services:
  astro-client:
    container_name: test-astro-client
    build:
      context: .
      dockerfile: Dockerfile
#    expose:
#      - 3000
#    ports:
#      - 3000:3000
    labels:
      - traefik.enable=true
      - traefik.http.routers.to-astro-client.entrypoints=web
      - traefik.http.routers.to-astro-client.rule=Host(`astro-client.mypublicserver.duckdns.org`)
#    volumes:
#      - ./client/src:/srv/app/client/src
#      - ./client/public:/srv/app/client/public
    networks:
      - proxy
networks:
  proxy:
    name: proxy
    external: true