name: Node.js CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [20.10.0]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile
#      - name: Create env file
#        run: |
#          echo "NEXT_WEBSITE_URL=${{ secrets.NEXT_WEBSITE_URL }}" >> .env.production
#          echo "NEXT_PUBLIC_NEXT_GA_TRACKING_ID=${{ secrets.NEXT_PUBLIC_NEXT_GA_TRACKING_ID }}" >> .env.production
#        working-directory: ${{ github.workspace }}

#      - name: Print contents of .env.production file
#        run: cat .env.production

      - name: Build
        run: yarn run build

#      - name: Change Directory
#        run: cd /home/base/actions-runner/_work/YOUR_PROJECT_NAME/YOUR_PROJECT_NAME
#      - run: pm2 reload 0